--What is what
--	AUTO	:	HIBERNATE_SEQUENCE
--	IDENTITY:	AUTO INCREMENT
--	SEQUENCE:	USER DEFINED SEQUENCE
--	TABLE	:	TABLE WILL GIVE THE NEXT NUMBER


--AUTO
CREATE TABLE JM3006_STUDENT_AUTO(
ID BIGINT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE NUMBER,
GENDER VARCHAR(10)
);

CREATE SEQUENCE HIBERNATE_SEQUENCE;
ALTER SEQUENCE HIBERNATE_SEQUENCE RESTART WITH 10001;


--IDENETITY
CREATE TABLE JM3006_STUDENT_IDENTITY(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE NUMBER,
GENDER VARCHAR(10)
);

--SEQUENCE
CREATE TABLE JM3006_STUDENT_SEQUENCE(
ID BIGINT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE NUMBER,
GENDER VARCHAR(10)
);

CREATE SEQUENCE SEQ_JM3006_STD_SEQUENCE;
ALTER SEQUENCE SEQ_JM3006_STD_SEQUENCE RESTART WITH 1001;

-- TABLE
CREATE TABLE JM3006_SEQUENCES(
SEQUENCE_NAME VARCHAR,
NEXT_VAL BIGINT
);

CREATE SEQUENCE SEQ_JM3006_STD_TABLE;
--ALTER SEQUENCE SEQ_JM3006_STD_SEQUENCE RESTART WITH 1001;
INSERT INTO JM3006_SEQUENCES VALUES('SEQ_JM3006_STD_TABLE', 1001);

CREATE TABLE JM3006_STUDENT_TABLE(
ID BIGINT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE NUMBER,
GENDER VARCHAR(10)
);
