--AUTO
CREATE TABLE JM3006_STUDENT_AUTO(
ID BIGINT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE NUMBER,
GENDER VARCHAR(10)
);

CREATE SEQUENCE HIBERNATE_SEQUENCE;
ALTER SEQUENCE HIBERNATE_SEQUENCE RESTART WITH 10001;


--IDENETITY
CREATE TABLE JM3006_STUDENT_IDENTITY(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE NUMBER,
GENDER VARCHAR(10)
);

--SEQUENCE
CREATE TABLE JM3006_STUDENT_SEQUENCE(
ID BIGINT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE NUMBER,
GENDER VARCHAR(10)
);

CREATE SEQUENCE SEQ_JM3006_STD_SEQUENCE;
ALTER SEQUENCE SEQ_JM3006_STD_SEQUENCE RESTART WITH 1001;
