-- Associations

-- One to One Mapping - Uni directional
CREATE TABLE JM3006_ASSOCIATION_TRAINER_OTO_UNI(
ID BIGINT PRIMARY KEY,
NAME VARCHAR(50),
MOBILE VARCHAR(20),
TRAINER_DETAIL_ID BIGINT,
FOREIGN KEY (TRAINER_DETAIL_ID) REFERENCES JM3006_ASSOCIATION_TRAINER_DETAIL_OTO_UNI(ID)
);

CREATE TABLE JM3006_ASSOCIATION_TRAINER_DETAIL_OTO_UNI(
ID BIGINT PRIMARY KEY,
EMAIL VARCHAR(50),
AGE NUMBER,
GENDER VARCHAR(10),
);


-- One to One Mapping - Bi directional
CREATE TABLE JM3006_ASSOCIATION_TRAINER_OTO_BI(
ID BIGINT PRIMARY KEY,
NAME VARCHAR(50),
MOBILE VARCHAR(20),
TRAINER_DETAIL_ID BIGINT,
FOREIGN KEY (TRAINER_DETAIL_ID) REFERENCES JM3006_ASSOCIATION_TRAINER_DETAIL_OTO_BI(ID)
);

CREATE TABLE JM3006_ASSOCIATION_TRAINER_DETAIL_OTO_BI(
ID BIGINT PRIMARY KEY,
EMAIL VARCHAR(50),
AGE NUMBER,
GENDER VARCHAR(10),
);


-- One to Many Mapping - Uni Directional
CREATE TABLE JM3006_ASSOCIATION_COURSE_OTM_UNI(
COURSE_ID BIGINT PRIMARY KEY,
COURSE_NAME VARCHAR
);

CREATE TABLE JM3006_ASSOCIATION_ASSIGNMENT_OTM_UNI(
ASSIGNMENT_ID BIGINT PRIMARY KEY,
ASSIGNMENT_NAME VARCHAR,
COURSE_ID BIGINT,
FOREIGN KEY(COURSE_ID) REFERENCES JM3006_ASSOCIATION_COURSE_OTM_UNI(COURSE_ID)
);

-- One to Many Mapping - Bi Directional
CREATE TABLE JM3006_ASSOCIATION_COURSE_OTM_BI(
COURSE_ID BIGINT PRIMARY KEY,
COURSE_NAME VARCHAR
);

CREATE TABLE JM3006_ASSOCIATION_ASSIGNMENT_OTM_BI(
ASSIGNMENT_ID BIGINT PRIMARY KEY,
ASSIGNMENT_NAME VARCHAR,
COURSE_ID BIGINT,
FOREIGN KEY(COURSE_ID) REFERENCES JM3006_ASSOCIATION_COURSE_OTM_BI(COURSE_ID)
);
