-- Associations

-- One to One Mapping - Uni directional
CREATE TABLE JM3006_ASSOCIATION_TRAINER_OTO_UNI(
ID BIGINT PRIMARY KEY,
NAME VARCHAR(50),
MOBILE VARCHAR(20),
TRAINER_DETAIL_ID BIGINT,
FOREIGN KEY (TRAINER_DETAIL_ID) REFERENCES JM3006_ASSOCIATION_TRAINER_DETAIL_OTO_UNI(ID)
);

CREATE TABLE JM3006_ASSOCIATION_TRAINER_DETAIL_OTO_UNI(
ID BIGINT PRIMARY KEY,
EMAIL VARCHAR(50),
AGE NUMBER,
GENDER VARCHAR(10),
);
